// Fetch List of Animes
export const FETCH_ANIMES = 'FETCH_ANIMES';
export const FETCH_ANIMES_LOADING = 'FETCH_ANIMES_LOADING';
export const FETCH_ANIMES_SUCCESS = 'FETCH_ANIMES_SUCCESS';
export const FETCH_ANIMES_FAILURE = 'FETCH_ANIMES_FAILURE';

// Fetch Single Anime Details
export const FETCH_ANIME_DETAILS = 'FETCH_ANIME_DETAILS';
export const FETCH_ANIME_DETAILS_LOADING = 'FETCH_ANIME_DETAILS_LOADING';
export const FETCH_ANIME_DETAILS_SUCCESS = 'FETCH_ANIME_DETAILS_SUCCESS';
export const FETCH_ANIME_DETAILS_FAILURE = 'FETCH_ANIME_DETAILS_FAILURE';

// Set Search Term and Fetch Searched Animes
export const SET_ANIME_SEARCH_TERM = 'SET_ANIME_SEARCH_TERM';
export const RESET_ANIME_SEARCH_TERM = 'RESET_ANIME_SEARCH_TERM';
export const FETCH_ANIMES_BY_KEYWORD = 'FETCH_ANIMES_BY_KEYWORD';
export const FETCH_ANIMES_BY_KEYWORD_LOADING = 'FETCH_ANIMES_BY_KEYWORD_LOADING';
export const FETCH_ANIMES_BY_KEYWORD_SUCCESS = 'FETCH_ANIMES_BY_KEYWORD_SUCCESS';
export const FETCH_ANIMES_BY_KEYWORD_FAILURE = 'FETCH_ANIMES_BY_KEYWORD_FAILURE';

// Fetch Anime Characters
export const FETCH_ANIMES_CHARACTERS_BY_ANIME = 'FETCH_ANIMES_CHARACTERS_BY_ANIME';
export const FETCH_ANIMES_CHARACTERS_BY_ANIME_LOADING = 'FETCH_ANIMES_CHARACTERS_BY_ANIME_LOADING';
export const FETCH_ANIMES_CHARACTERS_BY_ANIME_SUCCESS = 'FETCH_ANIMES_CHARACTERS_BY_ANIME_SUCCESS';
export const FETCH_ANIMES_CHARACTERS_BY_ANIME_FAILURE = 'FETCH_ANIMES_CHARACTERS_BY_ANIME_FAILURE';

export const FETCH_ANIME_CHARACTER_DETAILS = 'FETCH_ANIME_CHARACTER_DETAILS';
export const FETCH_ANIME_CHARACTER_DETAILS_LOADING = 'FETCH_ANIME_CHARACTER_DETAILS_LOADING';
export const FETCH_ANIME_CHARACTER_DETAILS_SUCCESS = 'FETCH_ANIME_CHARACTER_DETAILS_SUCCESS';
export const FETCH_ANIME_CHARACTER_DETAILS_FAILURE = 'FETCH_ANIME_CHARACTER_DETAILS_FAILURE';
