// Fetch List of Animes
export const FETCH_ANIMES = 'FETCH_ANIMES';
export const FETCH_ANIMES_LOADING = 'FETCH_ANIMES_LOADING';
export const FETCH_ANIMES_SUCCESS = 'FETCH_ANIMES_SUCCESS';
export const FETCH_ANIMES_FAILURE = 'FETCH_ANIMES_FAILURE';

// Fetch Single Anime Details
export const FETCH_ANIME_DETAILS = 'FETCH_ANIME_DETAILS';
export const FETCH_ANIME_DETAILS_LOADING = 'FETCH_ANIME_DETAILS_LOADING';
export const FETCH_ANIME_DETAILS_SUCCESS = 'FETCH_ANIME_DETAILS_SUCCESS';
export const FETCH_ANIME_DETAILS_FAILURE = 'FETCH_ANIME_DETAILS_FAILURE';

// Set Search Term and Fetch Searched Animes
export const FETCH_ANIMES_BY_KEYWORD = 'FETCH_ANIMES_BY_KEYWORD';
export const FETCH_ANIMES_BY_KEYWORD_LOADING = 'FETCH_ANIMES_BY_KEYWORD_LOADING';
export const FETCH_ANIMES_BY_KEYWORD_SUCCESS = 'FETCH_ANIMES_BY_KEYWORD_SUCCESS';
export const FETCH_ANIMES_BY_KEYWORD_FAILURE = 'FETCH_ANIMES_BY_KEYWORD_FAILURE';
