export const FETCH_ANIMES = 'FETCH_ANIMES';
export const FETCH_ANIMES_LOADING = 'FETCH_ANIMES_LOADING';
export const FETCH_ANIMES_SUCCESS = 'FETCH_ANIMES_SUCCESS';
export const FETCH_ANIMES_FAILURE = 'FETCH_ANIMES_FAILURE';
